import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const nodeBuiltins = [...builtinModules, ...builtinModules.map((m) => `node:${m}`)];

const shared = {
    banner: { js: banner },
    bundle: true,
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    minify: prod,
};

// The plugin itself, loaded by Obsidian's renderer.
const pluginCtx = await esbuild.context({
    ...shared,
    entryPoints: ["src/main.ts"],
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...nodeBuiltins,
    ],
    outfile: "main.js",
});

// The stdio MCP server, spawned by a Claude client via Obsidian's bundled Node.
// Emitted into dist/ (gitignored + lint-ignored); distribution copies it next to
// main.js in the plugin folder, where the plugin points the client at it.
const stdioCtx = await esbuild.context({
    ...shared,
    entryPoints: ["src/mcp-stdio.ts"],
    platform: "node",
    external: [...nodeBuiltins],
    outfile: "dist/mcp-stdio.js",
});

if (prod) {
    await pluginCtx.rebuild();
    await stdioCtx.rebuild();
    process.exit(0);
} else {
    await pluginCtx.watch();
    await stdioCtx.watch();
}
